### ISSUE TITLE
ボタン入力のメッセージ

### ISSUE THREAD

**Issue by Hato6502** [GenesisGameProject/genesis#1]
ボタン入力について、仮想キーボードを構築する方法について、

メリット
・DXRuby側で独自のライブラリが不要になる
・キーボードでも操作できる

デメリット
・アナログスティックの入力を伝えるメッセージがない
・デバイスドライバをRubyで書くメドがたたない

しばらくは、C言語でデバイスドライバを書いてみます。

**Comment by kuromike0629** [comment]
アナログスティックだけは別でライブラリを用意するのはどう？

**Comment by kuromike0629** [comment]
dxrubyの標準でゲームパッドをサポートしている見たいだから通常のゲームパッドと同じようにデバイスドライバ書いて、GPIOを仮想的なゲームパッドとして作れないかな？

**Comment by Hato6502** [comment]
ゲームパッド化が最適だね。
デバイスドライバ構築のために、Linuxカーネルコンパイル中。
C言語で作っていきます。

Genesis内のOSを通して、キーボードとGPIOを両対応できると便利。
ゲームが直接dxrubyを使わずに、OSを通してボタン入力させない？
もしくは、ライブラリで各ゲームにボタン入力を実装。

**Comment by kuromike0629** [comment]
じゃあこっちはお願いしたい。リポジトリとしてのファイル構造を一旦見直して、GPIOの仮想化とドライバ開発ように場所用意するからちょっとまっててー

**Comment by Hato6502** [comment]
ゲームパッドのデバイスドライバができた（ボタンのみ）！

**Comment by kuromike0629** [comment]
すごいね！！
アナログはどう？

**Comment by Hato6502** [comment]
まだだけど、検討はついてる。

**Comment by Hato6502** [comment]
I've completed the button device driver including analog stick.
The hardware SPI ports had been already used by fbtft, 
so I'd programmed the software SPI operation!
Though I told "I've already considered" in the preview comment, 
there was not a such thing...

I'll send "pull request". 
Please review my code: button branch /dev/button/button.c. 
Good night.

**Comment by kuromike0629** [comment]
I will close this issue because functions button used by GPIO forked from this project.

GPIO => Gamepad Library for raspberry pi  will develop in GenesisGameProject/gpiojsgn.
[See more](https://github.com/GenesisGameProject/gpiojsgn)
