### ISSUE TITLE
License of Genesis

### ISSUE THREAD

**Issue by kuromike0629** [GenesisGameProject/genesis#12]
I forgot to write license of Genesis.

My suggestion is ...
1.GPL
2.MIT
3.BSD

In your source code (in button.c) License set GPL but I guess GPL is little too strong for genesis.

**Comment by Hato6502** [comment]
The device driver is a part of linux kernel. 
And the linux kernel is licenced as GPL, 
so I must licence my code as GPL, too. 
(If I don't licence then, the warning occured in compiling. )

The other sources in Genesis need NOT license, so don't worry.

**Comment by kuromike0629** [comment]
OK
But I think software can not have over two Licenses.
Because It will cause confusion for users especially like this open source project.

I think we can make new repository for button and develop device driver for GPIO GamePad.

If that case , We can make new organization for Genesis and make new repository.

**Comment by kuromike0629** [comment]
See more https://git-scm.com/book/ja/v2/GitHub-%E7%B5%84%E7%B9%94%E3%81%AE%E7%AE%A1%E7%90%86

**Comment by Hato6502** [comment]
It's a great system! 
I've created a new repository "gpiojs" on my account. 

https://github.com/Hato6502/gpiojs

Could you make a new organization?, or may I try?

**Comment by kuromike0629** [comment]
I will ! 
We have to decide our Organization Name usually it will be main product name.

So how about "Genesis Project" for organization name.
