### ISSUE TITLE
Organization name

### ISSUE THREAD

**Issue by kuromike0629** [GenesisGameProject/genesis#13]
We have to set organization name.

But GenesisProject is already used.

So please write your idea for organization name.

**Comment by Hato6502** [comment]
Umm...

genesis - the open game console project on Raspi
...Too long?

**Comment by kuromike0629** [comment]
kind of ...
What about..
GenesisGameProject
?

**Comment by kuromike0629** [comment]
I created new Organization named by "GenesisGameProject".

I invited hato6502. please join it.

Also please transfer repository of gpio game pad.
In order to know how to transfer repository.
see (http://qiita.com/do7be/items/fa845240bc58b2153a44)

**Comment by Hato6502** [comment]
Okay, I've created a new repository "gpiojsgn".
