### ISSUE TITLE
メイン画面の作成について

### ISSUE THREAD

**Issue by kuromike0629** [GenesisGameProject/genesis#2]
メイン画面の実装今しているけど何か意見ある？

とりあえず搭載予定なのは以下の通りです。
１.起動画面
2.メニュー画面
3.設定画面
4.終了画面

**Comment by Hato6502** [comment]
Genesisの根っこは、これでいいと思う。
「設定」はアプリケーションの一つとして、「メニュー」に統合しない？

メニュー画面から全て始める、みたいな。

**Comment by kuromike0629** [comment]
それでいいと思う。
基本的にはメニュー画面として実装する感じでいくよ！

実際実装部分RubyじゃなくてCの方がいい？メニューとか
その方がメモリ食わないよね？

**Comment by Hato6502** [comment]
そこは、rubyでもCでも構いません。
僕がデバイスドライバをCで書いてるのは、
カーネルモジュールを作るためだよ。

**Comment by kuromike0629** [comment]
うん
了解
とりあえず自分もブランチ切って、本格的に画面作り始める。

**Comment by kuromike0629** [comment]
ブランチ名：viewで開発開始。

とりあえず、/bin/genesis
で実行できる。

**Comment by kuromike0629** [comment]
とりあえず、スプラッシュとメニュー画面を作ってみた。
ここからどうしようかな？
一応その先はバックグラウンド作らないとできないからとりあえず、画面画像を確認お願いしたい。

**Comment by Hato6502** [comment]
めっちゃお洒落だな……、すごいね
文字フォントをラズパイに入れれば、メニュー画面を動的生成できそう

**Comment by kuromike0629** [comment]
そうだね
とりあえず、動かす方向でいくからissueだけ書いてメニュー動的生成はあとでって感じにしといてもいいかな？

先にメニューからゲームを起動する画面作るよ！

**Comment by kuromike0629** [comment]
I made...

1.start splash view
2.menu view
3.end splash view

I wrote other issues for 

・play view
・store view
・setting view

See issues
